// One-off: pull the Google Fonts woff2 files local so the browser makes zero
// third-party requests to render text. Keeps latin subsets only.
// Run: node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from 'node:fs/promises'

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:opsz,wght@14..32,100..900&family=JetBrains+Mono:wght@100..800&display=swap'

const KEEP = new Set(['latin', 'latin-ext'])
const OUT_DIR = 'public/fonts'

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text())

// each face is preceded by a /* subset */ comment
const blocks = css.split('/*').slice(1)
const faces = []

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim()
  if (!KEEP.has(subset)) continue

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? 'normal'
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? '400'
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
  if (!url || !family) continue

  const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${style}-${weight.replace(/\s+/g, '')}-${subset}`
  faces.push({ url, family, style, weight, range, file: `${slug}.woff2` })
}

await mkdir(OUT_DIR, { recursive: true })

let total = 0
for (const f of faces) {
  const buf = Buffer.from(await fetch(f.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()))
  await writeFile(`${OUT_DIR}/${f.file}`, buf)
  total += buf.length
  console.log(`${f.file} ${(buf.length / 1024).toFixed(1)}KB`)
}

const out = faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')

await writeFile('src/fonts.css', `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n${out}\n`)

console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(0)}KB total -> ${OUT_DIR}`)
console.log('wrote src/fonts.css')
